### ISSUE TITLE
panic runnin tests in abcrypt-capi

### ISSUE THREAD

**Issue by 7p7an** [sorairolake/abcrypt#505]
### Checklist

- [X] I have searched the existing issues

### Describe the bug

First, thank you for this fine project.

I've a panic while running test in `abcrypt-capi`
(not a failing test but a real panic)

I don't think it depends on a misconfiguration on my side, but I'm unfamiliar with c-bindings

```shell
/home/projects/abcrypt > cargo test -p abcrypt-capi --lib
warning: abcrypt-capi@0.3.2: failed to execute Asciidoctor: No such file or directory (os error 2)
    Finished `test` profile [unoptimized + debuginfo] target(s) in 0.03s
     Running unittests src/lib.rs (target/debug/deps/abcrypt_capi-2f13f07bbad5ae2f)

running 33 tests
test decrypt::tests::invalid_input_length ... ok
test decrypt::tests::invalid_magic_number ... ok
test decrypt::tests::unknown_version ... ok
test decrypt::tests::invalid_params ... ok
test error::tests::clone ... ok
test error::tests::copy ... ok
test error::tests::debug ... ok
test error::tests::display ... ok
test error::tests::equality ... ok
test error::tests::error_code ... ok
test error::tests::error_message ... ok
test error::tests::error_message_out_len ... ok
test error::tests::from_error_to_code ... ok
test params::tests::memory_cost ... ok
test params::tests::parallelism ... ok
test params::tests::success ... ok
test tests::header_size ... ok
test params::tests::time_cost ... ok
test tests::tag_size ... ok
thread 'decrypt::tests::invalid_output_length' panicked at /home/projects/abcrypt/crates/abcrypt/src/decrypt.rs:115:17:
source slice length (14) does not match destination slice length (15)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'decrypt::tests::invalid_output_length' panicked at library/core/src/panicking.rs:221:5:
panic in a function that cannot unwind
``` 

### To Reproduce

execute:

`cargo test -p abcrypt-capi --lib`

from workspace folder

### Expected behavior

test passes

### abcrypt version

```shell
/home/projects/abcrypt > git log -n 1
commit bf2bdb6f6e00bc369954eb39711c9fe908350598 (HEAD -> develop, origin/develop, origin/HEAD)
Author: Shun Sakai <sorairolake@protonmail.ch>
Date:   Mon Jul 22 13:44:30 2024 +0900

    docs: Update installation method
``` 

### Rust version

`rustc 1.81.0-nightly (fcc325f1b 2024-07-17)`

### Environment

Archlinux

```shell
/home/projects/abcrypt > rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/aklo/.rustup

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.81.0-nightly (fcc325f1b 2024-07-17)
``` 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sorairolake** [comment]
@7p7an This test passes in the latest stable version (Rust 1.79.0). However, as you say, this test doesn't seem to pass in the nightly version. So I think this might be the cause.

**Comment by 7p7an** [comment]
Thank you for looking into this, I should have checked stable myself...
